export const LEVELS = [
  {
    id: 0,
    name: 'Long Level 0',
    mapKey: 'level0',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past/bg', pastNoCollide: 'past/nocollide', pastMain: 'past/main',
      presentBg: 'present/bg', presentNoCollide: 'present/nocollide', presentMain: 'present/main',
    },
    worldWidth: 1600, worldHeight: 384,
    cameraWidth: 1600, cameraHeight: 384,
    playerStart: { x: 110, y: 290 },
    objectivePos: { x: 920, y: 50 },
    guards: [
      { type: 'past', x: 720, y: 320, route: [{ x: 720, y: 320 }, { x: 420, y: 320 }, { x: 550, y: 270 }] },
      { type: 'past', x: 1060, y: 190, route: [{ x: 965, y: 200 }, { x: 1060, y: 200 }] },
      { type: 'present', x: 1080, y: 255, route: [{ x: 920, y: 270 }, { x: 1100, y: 270 }] },
    ],
    winTitle: 'LEVEL CLEAR!',
    nextScene: 'Level1Scene',
  },
  {
    id: 1,
    name: 'Level 1',
    mapKey: 'level1',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past_bg', pastNoCollide: 'past_nocollide', pastMain: 'past_main',
      presentBg: 'present_bg', presentNoCollide: 'present_nocollide', presentMain: 'present_main',
    },
    worldWidth: 560, worldHeight: 280,
    cameraWidth: 560, cameraHeight: 224,
    playerStart: { x: 50, y: 170 },
    objectivePos: { x: 420, y: 170 },
    guards: [
      { type: 'past', x: 450, y: 50, route: [{ x: 450, y: 192 }, { x: 300, y: 192 }] },
    ],
    winTitle: 'LEVEL 1 CLEAR!',
    nextScene: 'Level2Scene',
  },
  {
    id: 2,
    name: 'Level 2',
    mapKey: 'level2',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past/past_bg', pastNoCollide: 'past/past_nocollide', pastMain: 'past/past_main',
      presentBg: 'present/present_bg', presentNoCollide: 'present/present_nocollide', presentMain: 'present/present_main',
    },
    worldWidth: 560, worldHeight: 224,
    cameraWidth: 560, cameraHeight: 224,
    playerStart: { x: 50, y: 100 },
    objectivePos: { x: 420, y: 170 },
    guards: [
      { type: 'past', x: 450, y: 50, route: [{ x: 450, y: 192 }, { x: 300, y: 192 }] },
    ],
    winTitle: 'LEVEL 2 CLEAR!',
    nextScene: 'Level3Scene',
  },
  {
    id: 3,
    name: 'Level 3',
    mapKey: 'level3',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past/past_bg', pastNoCollide: 'past/past_nocollide', pastMain: 'past/past_main',
      presentBg: 'present/present_bg', presentNoCollide: 'present/present_nocollide', presentMain: 'present/present_main',
    },
    worldWidth: 560, worldHeight: 224,
    cameraWidth: 560, cameraHeight: 224,
    playerStart: { x: 50, y: 170 },
    objectivePos: { x: 420, y: 170 },
    guards: [
      { type: 'past', x: 450, y: 50, route: [{ x: 450, y: 192 }, { x: 300, y: 192 }] },
    ],
    winTitle: 'LEVEL 3 CLEAR!',
    nextScene: 'MenuScene',
  },
];
