export const LEVELS = [
  {
    id: 0,
    name: 'Long Level 0',
    mapKey: 'level0',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past/bg', pastNoCollide: 'past/nocollide', pastMain: 'past/main',
      presentBg: 'present/bg', presentNoCollide: 'present/nocollide', presentMain: 'present/main',
    },
    worldWidth: 1600, worldHeight: 384,
    cameraWidth: 1600, cameraHeight: 384,
    playerStart: { x: 110, y: 290 },
    objectivePos: { x: 920, y: 50 },
    objectivePeriod: "present",
    guards: [
      { type: 'past', x: 720, y: 320, route: [{ x: 720, y: 320 }, { x: 420, y: 320 }, { x: 550, y: 270 }] },
      { type: 'past', x: 1060, y: 190, route: [{ x: 965, y: 200 }, { x: 1060, y: 200 }] },
      { type: 'present', x: 1080, y: 255, route: [{ x: 920, y: 270 }, { x: 1100, y: 270 }] },
    ],
    winTitle: 'LEVEL CLEAR!',
    nextScene: 'Level1Scene',
  },
  {
    id: 1,
    name: 'Level 1',
    mapKey: 'level1',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past_bg', pastNoCollide: 'past_nocollide', pastMain: 'past_main',
      presentBg: 'present_bg', presentNoCollide: 'present_nocollide', presentMain: 'present_main',
    },
    worldWidth: 560, worldHeight: 280,
    cameraWidth: 560, cameraHeight: 224,
    playerStart: { x: 50, y: 170 },
    objectivePos: { x: 420, y: 170 },
    objectivePeriod: "present",
    guards: [
      { type: 'past', x: 450, y: 50, route: [{ x: 450, y: 192 }, { x: 300, y: 192 }] },
    ],
    winTitle: 'LEVEL 1 CLEAR!',
    nextScene: 'Level2Scene',
  },
  {
    id: 2,
    name: 'Level 2',
    mapKey: 'level2',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past/past_bg', pastNoCollide: 'past/past_nocollide', pastMain: 'past/past_main',
      presentBg: 'present/present_bg', presentNoCollide: 'present/present_nocollide', presentMain: 'present/present_main',
    },
    worldWidth: 560, worldHeight: 224,
    cameraWidth: 560, cameraHeight: 224,
    playerStart: { x: 50, y: 100 },
    objectivePos: { x: 420, y: 170 },
    objectivePeriod: "present",
    guards: [
      { type: 'past', x: 450, y: 50, route: [{ x: 450, y: 192 }, { x: 300, y: 192 }] },
    ],
    winTitle: 'LEVEL 2 CLEAR!',
    nextScene: 'Level3Scene',
  },
  {
    id: 3,
    name: 'Level 3',
    mapKey: 'level3',
    tilesetName: 'levelTileset',
    tilesetKey: 'tiles',
    layerMode: 'period-split',
    layers: {
      pastBg: 'past/bg', pastNoCollide: 'past/nocollide', pastMain: 'past/main',
      presentBg: 'present/bg', presentNoCollide: 'present/nocollide', presentMain: 'present/main',
    },
    worldWidth: 990, worldHeight: 600,
    cameraWidth: 990, cameraHeight: 600,
    playerStart: { x: 300, y: 528 },
    objectivePos: { x: 150, y: 490 },
    objectivePeriod: "past",
    guards: [
      { type: 'past', x: 150, y: 496, route: [{ x: 150, y: 496 }, { x: 105, y: 480 }, { x: 70, y: 464 }, { x: 26, y: 448 }, { x: 10, y: 448 }, { x: 50, y: 400 }, { x: 90, y: 384 }, { x: 130, y: 370 }, { x: 400, y: 370 }] },
      { type: 'past', x: 850, y: 368, route: [{ x: 850, y: 368 }, { x: 755, y: 320 }, { x: 650, y: 320 }, { x: 380, y: 368 }] },
      { type: 'past', x: 575, y: 528, route: [{ x: 575, y: 568 }, { x: 628, y: 480 }, { x: 720, y: 432 }, { x: 670, y: 480 }, { x: 830, y: 528 }] },
      { type: 'present', x: 358, y: 360, route: [{ x: 358, y: 368 }, { x: 215, y: 385 }, { x: 180, y: 432 }, { x: 110, y: 380 }, { x: 54, y: 450 }] },
    ],
    winTitle: 'LEVEL 3 CLEAR!',
    nextScene: 'MenuScene',
  },
];
